# ruff: noqa: RUF012
# ruff: noqa
# Generated by Django 5.2.7 on 2025-11-22 13:13
# Fixed: AlterUniqueTogether must run before RemoveField('session').

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012
        ("agents", "0002_auto_20250928_1713"),
    ]

    operations = [  # noqa: RUF012
        # Clear unique constraints that reference fields we are about to remove
        migrations.AlterUniqueTogether(
            name="teammember",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="workflowlock",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="changelog",
            name="session",
        ),
        migrations.RemoveField(
            model_name="changelog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="collaborationsession",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="session",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="session",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="session",
        ),
        migrations.RemoveField(
            model_name="workflowlock",
            name="session",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="resolved_by",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="invited_by",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="user",
        ),
        migrations.RemoveField(
            model_name="workflowlock",
            name="locked_by",
        ),
        migrations.DeleteModel(
            name="ActivityLog",
        ),
        migrations.DeleteModel(
            name="ChangeLog",
        ),
        migrations.DeleteModel(
            name="CollaborationSession",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.DeleteModel(
            name="TeamMember",
        ),
        migrations.DeleteModel(
            name="WorkflowLock",
        ),
    ]
