# ruff: noqa: RUF012
# ruff: noqa
# Generated by Django 6.0 on 2026-06-22 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012
        ("agents", "0004_collaborationsession_changelog_activitylog_comment_and_more"),
        ("authentication", "0002_workspace_workspacemembership"),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name="agent",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agents",
                to="authentication.workspace",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="authentication.workspace",
            ),
        ),
    ]
