# ruff: noqa: RUF012
# ruff: noqa
# Generated by Django 6.0 on 2026-06-29 11:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012
        ("authentication", "0002_workspace_workspacemembership"),
    ]

    operations = [
        migrations.CreateModel(
            name="BruteForceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=255, unique=True)),
                ("endpoint", models.CharField(blank=True, max_length=100)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("first_attempt", models.DateTimeField(auto_now_add=True)),
                ("last_attempt", models.DateTimeField(auto_now=True)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["key", "endpoint"], name="authenticat_key_693118_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OAuthState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(db_index=True, max_length=128, unique=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("email", "Email/Password"),
                            ("google", "Google"),
                            ("github", "GitHub"),
                            ("firebase", "Firebase"),
                        ],
                        max_length=20,
                    ),
                ),
                ("code_verifier", models.CharField(blank=True, max_length=128)),
                ("redirect_uri", models.URLField(blank=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["state", "provider"],
                        name="authenticat_state_d1f12d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_email", models.EmailField(blank=True, max_length=254)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("login_failed", "Login Failed"),
                            ("register", "Register"),
                            ("password_reset", "Password Reset"),
                            ("password_change", "Password Change"),
                            ("email_verified", "Email Verified"),
                            ("oauth_login", "OAuth Login"),
                            ("oauth_login_failed", "OAuth Login Failed"),
                            ("provider_linked", "Provider Linked"),
                            ("provider_unlinked", "Provider Unlinked"),
                            ("token_refresh", "Token Refresh"),
                            ("logout_all", "Logout All Devices"),
                            ("session_revoked", "Session Revoked"),
                            ("account_deleted", "Account Deleted"),
                            ("admin_action", "Admin Action"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email", "Email/Password"),
                            ("google", "Google"),
                            ("github", "GitHub"),
                            ("firebase", "Firebase"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_name", models.CharField(blank=True, max_length=255)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("os", models.CharField(blank=True, max_length=100)),
                ("success", models.BooleanField(default=True)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("request_id", models.CharField(blank=True, max_length=64)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="authenticat_user_id_3b88ca_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="authenticat_action_4a725a_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="authenticat_ip_addr_056073_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuthProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("email", "Email/Password"),
                            ("google", "Google"),
                            ("github", "GitHub"),
                            ("firebase", "Firebase"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider_user_id", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("avatar_url", models.URLField(blank=True, null=True)),
                ("access_token_hint", models.CharField(blank=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_providers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "provider"],
                        name="authenticat_user_id_cd9790_idx",
                    ),
                    models.Index(
                        fields=["provider", "provider_user_id"],
                        name="authenticat_provide_90c675_idx",
                    ),
                ],
                "unique_together": {("provider", "provider_user_id")},
            },
        ),
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hashed_token",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("family", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("session_id", models.UUIDField(blank=True, null=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("email", "Email/Password"),
                            ("google", "Google"),
                            ("github", "GitHub"),
                            ("firebase", "Firebase"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("device_name", models.CharField(blank=True, max_length=255)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("os", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoke_reason", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="authenticat_user_id_32f3b1_idx",
                    ),
                    models.Index(
                        fields=["family"], name="authenticat_family_608305_idx"
                    ),
                ],
            },
        ),
    ]
