# ruff: noqa: RUF012
# Generated by Django 6.0 on 2026-10-02 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_customuser_is_email_verified_emailverificationtoken"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="refreshtoken",
            new_name="authenticat_user_id_163694_idx",
            old_name="authenticat_user_id_32f3b1_idx",
        ),
        migrations.RenameIndex(
            model_name="refreshtoken",
            new_name="authenticat_family_d66618_idx",
            old_name="authenticat_family_608305_idx",
        ),
    ]
