# ruff: noqa
# Generated by Django 5.1.5 on 2025-09-28 10:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('campaign_type', models.CharField(choices=[('email', 'Email Campaign'), ('push', 'Push Notification'), ('sms', 'SMS Campaign'), ('in_app', 'In-App Notification'), ('webhook', 'Webhook')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('recipient_list', models.JSONField(default=list)),
                ('recipient_filters', models.JSONField(default=dict)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='draft', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('opened_count', models.PositiveIntegerField(default=0)),
                ('clicked_count', models.PositiveIntegerField(default=0)),
                ('bounced_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_marketing', models.BooleanField(default=False)),
                ('email_system', models.BooleanField(default=True)),
                ('email_frequency', models.CharField(default='immediate', max_length=20)),
                ('push_enabled', models.BooleanField(default=True)),
                ('push_marketing', models.BooleanField(default=False)),
                ('push_system', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_marketing', models.BooleanField(default=False)),
                ('sms_system', models.BooleanField(default=False)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('in_app_sound', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('user_action', 'User Action'), ('system_event', 'System Event'), ('schedule', 'Scheduled'), ('condition', 'Conditional'), ('api_event', 'API Event')], max_length=20)),
                ('conditions', models.JSONField(default=dict)),
                ('actions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('trigger_count', models.PositiveIntegerField(default=0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_rules',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('system', 'System')], default='info', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('action_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationcampaign')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationrule')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('email', 'Email Template'), ('push', 'Push Notification Template'), ('sms', 'SMS Template'), ('in_app', 'In-App Template')], max_length=20)),
                ('category', models.CharField(choices=[('welcome', 'Welcome'), ('alert', 'Alert'), ('reminder', 'Reminder'), ('update', 'Update'), ('marketing', 'Marketing'), ('system', 'System'), ('custom', 'Custom')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('html_content', models.TextField(blank=True)),
                ('variables', models.JSONField(default=list)),
                ('design_config', models.JSONField(default=dict)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_templates',
            },
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate'),
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscription_type', models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification'), ('sms', 'SMS'), ('in_app', 'In-App')], max_length=20)),
                ('endpoint', models.URLField(blank=True)),
                ('token', models.TextField(blank=True)),
                ('categories', models.JSONField(default=list)),
                ('frequency', models.CharField(default='immediate', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_subscriptions',
                'unique_together': {('user', 'subscription_type')},
            },
        ),
    ]
