# ruff: noqa: RUF012
# Generated by Django 5.2.7 on 2025-11-22 13:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0003_remove_changelog_session_remove_changelog_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdaptiveStrategy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("strategy_type", models.CharField(max_length=50)),
                ("agent_roles", models.JSONField()),
                ("conditions", models.JSONField()),
                ("times_used", models.IntegerField(default=0)),
                ("success_rate", models.FloatField(default=0.0)),
                ("avg_completion_time", models.FloatField(default=0.0)),
                ("confidence_score", models.FloatField(default=0.5)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "learned_from_sessions",
                    models.ManyToManyField(
                        related_name="learned_strategies", to="agents.session"
                    ),
                ),
            ],
            options={
                "db_table": "adaptive_strategy",
                "ordering": ["-confidence_score", "-success_rate"],
            },
        ),
        migrations.CreateModel(
            name="AgentLearningProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("q_learning", "Q-Learning"),
                            ("sarsa", "SARSA"),
                            ("deep_q", "Deep Q-Network"),
                            ("ppo", "Proximal Policy Optimization"),
                            ("a3c", "Asynchronous Advantage Actor-Critic"),
                        ],
                        default="q_learning",
                        max_length=50,
                    ),
                ),
                ("total_tasks_completed", models.IntegerField(default=0)),
                ("success_rate", models.FloatField(default=0.0)),
                ("average_response_time", models.FloatField(default=0.0)),
                ("learning_rate", models.FloatField(default=0.1)),
                ("discount_factor", models.FloatField(default=0.95)),
                ("specialized_capabilities", models.JSONField(default=dict)),
                ("task_type_performance", models.JSONField(default=dict)),
                ("adaptations_count", models.IntegerField(default=0)),
                ("last_adaptation", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_profile",
                        to="agents.agent",
                    ),
                ),
            ],
            options={
                "db_table": "agent_learning_profile",
                "ordering": ["-success_rate"],
            },
        ),
        migrations.CreateModel(
            name="LearningEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("metrics_before", models.JSONField()),
                ("metrics_after", models.JSONField()),
                ("improvement", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "learning_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="agent_learning.agentlearningprofile",
                    ),
                ),
            ],
            options={
                "db_table": "learning_event",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReinforcementState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("state_representation", models.JSONField()),
                ("action_taken", models.JSONField()),
                ("reward", models.FloatField()),
                ("next_state", models.JSONField(blank=True, null=True)),
                ("q_value", models.FloatField(default=0.0)),
                ("expected_q_value", models.FloatField(default=0.0)),
                ("task_type", models.CharField(max_length=100)),
                ("success", models.BooleanField(default=False)),
                ("execution_time", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "learning_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="agent_learning.agentlearningprofile",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agents.session",
                    ),
                ),
            ],
            options={
                "db_table": "reinforcement_state",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["learning_profile", "-created_at"],
                        name="reinforceme_learnin_ff5b6a_idx",
                    ),
                    models.Index(
                        fields=["task_type", "success"],
                        name="reinforceme_task_ty_5068cc_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SkillMatrix",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("skill_name", models.CharField(max_length=100)),
                ("skill_category", models.CharField(max_length=50)),
                ("expertise_level", models.FloatField(default=0.0)),
                ("attempts_count", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("failure_count", models.IntegerField(default=0)),
                ("avg_execution_time", models.FloatField(default=0.0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "learning_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="agent_learning.agentlearningprofile",
                    ),
                ),
            ],
            options={
                "db_table": "skill_matrix",
                "ordering": ["-expertise_level"],
                "unique_together": {("learning_profile", "skill_name")},
            },
        ),
    ]
