# ruff: noqa: RUF012
# Generated by Django 6.0 on 2025-12-22 15:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_learning", "0001_initial"),
        ("agents", "0004_collaborationsession_changelog_activitylog_comment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentLearningPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agent_identifier", models.CharField(db_index=True, max_length=255)),
                (
                    "policy_data",
                    models.JSONField(
                        help_text="Serialized policy (Q-table, weights, etc.)"
                    ),
                ),
                (
                    "algorithm_type",
                    models.CharField(default="q_learning", max_length=50),
                ),
                ("total_episodes", models.IntegerField(default=0)),
                ("average_reward", models.FloatField(default=0.0)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_policies",
                        to="agents.agent",
                    ),
                ),
                (
                    "parent_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="agent_learning.agentlearningpolicy",
                    ),
                ),
            ],
            options={
                "db_table": "agent_learning_policies",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["agent_identifier", "is_active"],
                        name="agent_learn_agent_i_357f06_idx",
                    )
                ],
            },
        ),
    ]
