# ruff: noqa: RUF012
# Generated by Django 6.0 on 2026-10-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agent_learning", "0002_agentlearningpolicy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adaptivestrategy",
            options={"ordering": ("-confidence_score", "-success_rate")},
        ),
        migrations.AlterModelOptions(
            name="agentlearningpolicy",
            options={"ordering": ("-updated_at",)},
        ),
        migrations.AlterModelOptions(
            name="agentlearningprofile",
            options={"ordering": ("-success_rate",)},
        ),
        migrations.AlterModelOptions(
            name="learningevent",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="reinforcementstate",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="skillmatrix",
            options={"ordering": ("-expertise_level",)},
        ),
    ]
