# ruff: noqa: RUF012
# ruff: noqa
# Generated by Django 5.1.5 on 2025-09-28 10:24

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [  # noqa: RUF012
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataPipeline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("pipeline_config", models.JSONField(default=dict)),
                ("steps", models.JSONField(default=list)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("scheduled", "Scheduled"),
                            ("event", "Event-driven"),
                            ("stream", "Continuous Stream"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("schedule_config", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("error", "Error"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("total_executions", models.PositiveIntegerField(default=0)),
                ("successful_executions", models.PositiveIntegerField(default=0)),
                ("failed_executions", models.PositiveIntegerField(default=0)),
                ("average_duration", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipelines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "data_pipelines",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataQualityRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("completeness", "Completeness"),
                            ("accuracy", "Accuracy"),
                            ("consistency", "Consistency"),
                            ("validity", "Validity"),
                            ("uniqueness", "Uniqueness"),
                            ("timeliness", "Timeliness"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("rule_config", models.JSONField(default=dict)),
                ("threshold", models.FloatField(default=100.0)),
                ("is_active", models.BooleanField(default=True)),
                ("stop_on_failure", models.BooleanField(default=False)),
                ("last_check_at", models.DateTimeField(blank=True, null=True)),
                ("last_result", models.JSONField(blank=True, default=dict)),
                ("pass_count", models.PositiveIntegerField(default=0)),
                ("fail_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_rules",
                        to="data_pipelines.datapipeline",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "data_quality_rules",
            },
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("database", "Database"),
                            ("api", "API"),
                            ("file", "File System"),
                            ("cloud_storage", "Cloud Storage"),
                            ("stream", "Data Stream"),
                            ("webhook", "Webhook"),
                            ("ftp", "FTP/SFTP"),
                            ("email", "Email"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "database_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("postgresql", "PostgreSQL"),
                            ("mysql", "MySQL"),
                            ("mongodb", "MongoDB"),
                            ("redis", "Redis"),
                            ("sqlite", "SQLite"),
                            ("oracle", "Oracle"),
                            ("mssql", "SQL Server"),
                        ],
                        max_length=20,
                    ),
                ),
                ("connection_config", models.JSONField(default=dict)),
                ("schema_info", models.JSONField(blank=True, default=dict)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                            ("testing", "Testing"),
                        ],
                        default="inactive",
                        max_length=20,
                    ),
                ),
                ("last_test_at", models.DateTimeField(blank=True, null=True)),
                ("last_test_success", models.BooleanField(default=False)),
                ("connection_time", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "data_pipeline_sources",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="datapipeline",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination_pipelines",
                to="data_pipelines.datasource",
            ),
        ),
        migrations.AddField(
            model_name="datapipeline",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_pipelines",
                to="data_pipelines.datasource",
            ),
        ),
        migrations.CreateModel(
            name="DataTransformation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "transformation_type",
                    models.CharField(
                        choices=[
                            ("filter", "Filter"),
                            ("map", "Map/Transform"),
                            ("aggregate", "Aggregate"),
                            ("join", "Join"),
                            ("sort", "Sort"),
                            ("validate", "Validate"),
                            ("clean", "Clean"),
                            ("enrich", "Enrich"),
                            ("custom", "Custom Script"),
                        ],
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("script", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transformations",
                        to="data_pipelines.datapipeline",
                    ),
                ),
            ],
            options={
                "db_table": "data_transformations",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PipelineExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("trigger_type", models.CharField(max_length=20)),
                ("input_parameters", models.JSONField(blank=True, default=dict)),
                ("current_step", models.CharField(blank=True, max_length=255)),
                ("progress_percentage", models.PositiveIntegerField(default=0)),
                ("steps_completed", models.PositiveIntegerField(default=0)),
                ("total_steps", models.PositiveIntegerField(default=0)),
                ("output_data", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("error_step", models.CharField(blank=True, max_length=255)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("records_processed", models.PositiveIntegerField(default=0)),
                ("records_failed", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="data_pipelines.datapipeline",
                    ),
                ),
            ],
            options={
                "db_table": "data_pipeline_executions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DataQualityCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("warning", "Warning"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.FloatField()),
                ("result_data", models.JSONField(default=dict)),
                ("issues_found", models.JSONField(blank=True, default=list)),
                ("records_checked", models.PositiveIntegerField(default=0)),
                ("records_passed", models.PositiveIntegerField(default=0)),
                ("records_failed", models.PositiveIntegerField(default=0)),
                ("check_duration", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="data_pipelines.dataqualityrule",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_checks",
                        to="data_pipelines.pipelineexecution",
                    ),
                ),
            ],
            options={
                "db_table": "data_quality_checks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PipelineSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once", "Once"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("cron", "Custom Cron"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cron_expression", models.CharField(blank=True, max_length=100)),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("schedule_timezone", models.CharField(default="UTC", max_length=50)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("total_runs", models.PositiveIntegerField(default=0)),
                ("successful_runs", models.PositiveIntegerField(default=0)),
                ("failed_runs", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="data_pipelines.datapipeline",
                    ),
                ),
            ],
            options={
                "db_table": "data_pipeline_schedules",
            },
        ),
    ]
