# ruff: noqa
# Generated by Django 6.0 on 2025-12-22 15:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "platform",
                    models.CharField(
                        choices=[("zapier", "Zapier"), ("make", "Make")], max_length=50
                    ),
                ),
                ("webhook_url", models.URLField()),
                (
                    "trigger_events",
                    models.JSONField(
                        default=list, help_text="Events that trigger this workflow"
                    ),
                ),
                ("filters", models.JSONField(default=dict, help_text="Event filters")),
                ("is_active", models.BooleanField(default=True)),
                ("execution_count", models.IntegerField(default=0)),
                ("last_executed", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "automation_workflows",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("azure_cosmosdb", "Azure CosmosDB"),
                            ("azure_functions", "Azure Functions"),
                            ("zapier", "Zapier"),
                            ("make", "Make"),
                            ("webhook", "Webhook"),
                            ("api", "API"),
                        ],
                        max_length=50,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                (
                    "credentials",
                    models.JSONField(default=dict, help_text="Encrypted credentials"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "integrations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("input_data", models.JSONField(default=dict)),
                ("output_data", models.JSONField(default=dict)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("duration_ms", models.IntegerField(default=0)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="integrations.integration",
                    ),
                ),
            ],
            options={
                "db_table": "integration_executions",
                "ordering": ["-executed_at"],
                "indexes": [
                    models.Index(
                        fields=["integration", "executed_at"],
                        name="integration_integra_9d4e13_idx",
                    ),
                    models.Index(
                        fields=["success", "executed_at"],
                        name="integration_success_d30cb6_idx",
                    ),
                ],
            },
        ),
    ]
