# ruff: noqa
# Generated by Django 5.2.7 on 2025-11-22 13:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnomalyDetection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("anomaly_type", models.CharField(max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("affected_component", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("metrics", models.JSONField()),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "analytics_anomaly_detection",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="PredictiveAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prediction_type",
                    models.CharField(
                        choices=[
                            ("load_forecast", "Load Forecast"),
                            ("cost_forecast", "Cost Forecast"),
                            ("capacity_planning", "Capacity Planning"),
                            ("failure_prediction", "Failure Prediction"),
                        ],
                        max_length=50,
                    ),
                ),
                ("time_horizon", models.CharField(max_length=50)),
                ("predictions", models.JSONField()),
                ("confidence_intervals", models.JSONField()),
                ("historical_data_used", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "analytics_predictive_analytics",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowOptimization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("workflow_id", models.UUIDField()),
                (
                    "optimization_type",
                    models.CharField(
                        choices=[
                            ("reduce_cost", "Reduce Cost"),
                            ("improve_speed", "Improve Speed"),
                            ("increase_accuracy", "Increase Accuracy"),
                            ("reduce_tokens", "Reduce Token Usage"),
                            ("parallel_execution", "Parallel Execution"),
                        ],
                        max_length=50,
                    ),
                ),
                ("current_performance", models.JSONField()),
                ("suggested_changes", models.JSONField()),
                ("estimated_improvement", models.JSONField()),
                ("confidence_score", models.FloatField()),
                ("implemented", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "analytics_workflow_optimization",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("response_time", "Response Time"),
                            ("token_usage", "Token Usage"),
                            ("cost", "Cost"),
                            ("success_rate", "Success Rate"),
                            ("error_rate", "Error Rate"),
                            ("throughput", "Throughput"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.FloatField()),
                ("workflow_id", models.UUIDField(blank=True, null=True)),
                ("agent_id", models.UUIDField(blank=True, null=True)),
                ("session_id", models.UUIDField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "analytics_performance_metrics",
                "indexes": [
                    models.Index(
                        fields=["metric_type", "timestamp"],
                        name="analytics_p_metric__c5d7c4_idx",
                    ),
                    models.Index(
                        fields=["workflow_id", "timestamp"],
                        name="analytics_p_workflo_354948_idx",
                    ),
                    models.Index(
                        fields=["agent_id", "timestamp"],
                        name="analytics_p_agent_i_dec7f6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CostAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("groq", "Groq"),
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("custom", "Custom Provider"),
                        ],
                        max_length=50,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("tokens_used", models.IntegerField()),
                ("cost", models.DecimalField(decimal_places=6, max_digits=10)),
                ("request_count", models.IntegerField(default=1)),
                ("workflow_id", models.UUIDField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_cost_analysis",
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="analytics_c_user_id_289e57_idx",
                    ),
                    models.Index(
                        fields=["provider", "timestamp"],
                        name="analytics_c_provide_60f0b7_idx",
                    ),
                ],
            },
        ),
    ]