# ruff: noqa: RUF012
# Generated by Django 6.0 on 2026-10-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anomalydetection",
            options={"ordering": ("-detected_at",)},
        ),
        migrations.AlterModelOptions(
            name="predictiveanalytics",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="workflowoptimization",
            options={"ordering": ("-created_at",)},
        ),
    ]
