# ruff: noqa: RUF012
# Generated by Django 6.0 on 2026-10-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_builder", "0002_alter_workflowtemplate_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visualworkflow",
            options={"ordering": ("-updated_at",)},
        ),
        migrations.AlterModelOptions(
            name="workflowexecution",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="workflowtemplate",
            options={"ordering": ("-usage_count", "-rating")},
        ),
    ]
