# ruff: noqa
# Generated by Django 5.2.7 on 2025-11-22 10:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModelConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Model"),
                            ("vision", "Vision Model"),
                            ("audio", "Audio Model"),
                            ("video", "Video Model"),
                            ("multimodal", "Multi-Modal Model"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(max_length=100)),
                ("model_id", models.CharField(max_length=200)),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Model configuration parameters"
                    ),
                ),
                (
                    "capabilities",
                    models.JSONField(
                        default=list, help_text="List of model capabilities"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MultiModalSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "input_modalities",
                    models.JSONField(
                        default=list, help_text="List of input modalities"
                    ),
                ),
                (
                    "output_modalities",
                    models.JSONField(
                        default=list, help_text="List of output modalities"
                    ),
                ),
                ("processing_config", models.JSONField(default=dict)),
                ("results", models.JSONField(default=dict)),
                (
                    "context",
                    models.JSONField(
                        default=dict, help_text="Shared context across modalities"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multimodal_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModalityResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("modality_type", models.CharField(max_length=50)),
                ("input_data", models.JSONField(default=dict)),
                ("output_data", models.JSONField(default=dict)),
                ("confidence_score", models.FloatField(default=0.0)),
                (
                    "processing_time",
                    models.FloatField(
                        default=0.0, help_text="Processing time in seconds"
                    ),
                ),
                ("tokens_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Multi_model_Intelligence.aimodelconfig",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modality_results",
                        to="Multi_model_Intelligence.multimodalsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CrossModalInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("insight_type", models.CharField(max_length=100)),
                ("involved_modalities", models.JSONField(default=list)),
                ("description", models.TextField()),
                ("confidence", models.FloatField(default=0.0)),
                ("evidence", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cross_modal_insights",
                        to="Multi_model_Intelligence.multimodalsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aimodelconfig",
            index=models.Index(
                fields=["model_type", "is_active"],
                name="Multi_model_model_t_17c912_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aimodelconfig",
            index=models.Index(
                fields=["provider", "is_active"], name="Multi_model_provide_261e8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="multimodalsession",
            index=models.Index(
                fields=["user", "status"], name="Multi_model_user_id_b196da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="multimodalsession",
            index=models.Index(
                fields=["status", "created_at"], name="Multi_model_status_1bdd68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modalityresult",
            index=models.Index(
                fields=["session", "modality_type"],
                name="Multi_model_session_a510c8_idx",
            ),
        ),
    ]
