# ruff: noqa
# Generated by Django 6.0 on 2025-12-22 12:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Multi_model_Intelligence", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("groq", "Groq"),
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                (
                    "complexity",
                    models.CharField(
                        choices=[
                            ("simple", "Simple"),
                            ("moderate", "Moderate"),
                            ("complex", "Complex"),
                            ("creative", "Creative"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField()),
                ("response", models.TextField()),
                (
                    "duration_ms",
                    models.IntegerField(help_text="Execution duration in milliseconds"),
                ),
                ("tokens_used", models.IntegerField()),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("priority", models.CharField(default="balanced", max_length=20)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "multimodel_executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelFallbackLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_provider", models.CharField(max_length=20)),
                ("original_model", models.CharField(max_length=100)),
                ("failure_reason", models.TextField()),
                ("fallback_provider", models.CharField(max_length=20)),
                ("fallback_model", models.CharField(max_length=100)),
                ("fallback_success", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "multimodel_fallback_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelPerformanceMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                ("model_name", models.CharField(max_length=100)),
                ("total_requests", models.IntegerField(default=0)),
                ("successful_requests", models.IntegerField(default=0)),
                ("failed_requests", models.IntegerField(default=0)),
                ("avg_duration_ms", models.FloatField(default=0)),
                ("avg_tokens", models.FloatField(default=0)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "multimodel_performance_metrics",
            },
        ),
        migrations.CreateModel(
            name="ModelPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "default_priority",
                    models.CharField(
                        choices=[
                            ("speed", "Speed"),
                            ("cost", "Cost"),
                            ("quality", "Quality"),
                            ("balanced", "Balanced"),
                        ],
                        default="balanced",
                        max_length=20,
                    ),
                ),
                (
                    "max_cost_per_request",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "monthly_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "preferred_providers",
                    models.JSONField(
                        default=list, help_text="Ordered list of preferred providers"
                    ),
                ),
                (
                    "disabled_providers",
                    models.JSONField(
                        default=list, help_text="List of disabled providers"
                    ),
                ),
                (
                    "complexity_overrides",
                    models.JSONField(
                        default=dict,
                        help_text="Custom model selection per complexity level",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "multimodel_preferences",
            },
        ),
        migrations.AlterModelOptions(
            name="crossmodalinsight",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="aimodelconfig",
            name="Multi_model_model_t_17c912_idx",
        ),
        migrations.RemoveIndex(
            model_name="aimodelconfig",
            name="Multi_model_provide_261e8d_idx",
        ),
        migrations.RemoveIndex(
            model_name="modalityresult",
            name="Multi_model_session_a510c8_idx",
        ),
        migrations.RemoveIndex(
            model_name="multimodalsession",
            name="Multi_model_user_id_b196da_idx",
        ),
        migrations.RemoveIndex(
            model_name="multimodalsession",
            name="Multi_model_status_1bdd68_idx",
        ),
        migrations.AlterField(
            model_name="aimodelconfig",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_model_configs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="aimodelconfig",
            table="multimodel_ai_configs",
        ),
        migrations.AlterModelTable(
            name="crossmodalinsight",
            table="multimodal_cross_insights",
        ),
        migrations.AlterModelTable(
            name="modalityresult",
            table="multimodal_modality_results",
        ),
        migrations.AlterModelTable(
            name="multimodalsession",
            table="multimodal_sessions",
        ),
        migrations.AddField(
            model_name="modelexecution",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model_executions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="modelfallbacklog",
            name="execution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fallback_logs",
                to="Multi_model_Intelligence.modelexecution",
            ),
        ),
        migrations.AddIndex(
            model_name="modelperformancemetrics",
            index=models.Index(
                fields=["provider", "model_name", "period_start"],
                name="multimodel__provide_b8a56c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="modelperformancemetrics",
            unique_together={("provider", "model_name", "period_start")},
        ),
        migrations.AddField(
            model_name="modelpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="modelexecution",
            index=models.Index(
                fields=["user", "created_at"], name="multimodel__user_id_2e1eec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelexecution",
            index=models.Index(
                fields=["provider", "model_name"], name="multimodel__provide_55ca45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelexecution",
            index=models.Index(
                fields=["complexity", "created_at"],
                name="multimodel__complex_8a0a1f_idx",
            ),
        ),
    ]
