# ruff: noqa
# Generated by Django 6.0 on 2026-04-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Multi_model_Intelligence", "0003_alter_modelexecution_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelexecution",
            name="provider",
            field=models.CharField(
                choices=[
                    ("nvidia", "NVIDIA"),
                    ("groq", "Groq"),
                    ("google", "Google"),
                    ("anthropic", "Anthropic"),
                    ("openai", "OpenAI"),
                ],
                max_length=20,
            ),
        ),
    ]
