# ruff: noqa
# Generated by Django 6.0 on 2026-07-22 17:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Multi_model_Intelligence", "0004_alter_modelexecution_provider"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crossmodalinsight",
            options={"ordering": ["-confidence", "-created_at"]},
        ),
        migrations.AlterModelTable(
            name="crossmodalinsight",
            table=None,
        ),
        migrations.CreateModel(
            name="ModelCoordinationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("route", "Smart Route"),
                            ("collaborative", "Collaborative"),
                            ("debate", "Debate / Consensus"),
                            ("pipeline", "Sequential Pipeline"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField()),
                ("model_ids", models.JSONField(default=list)),
                ("options", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
                ("final_answer", models.TextField(blank=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField()),
                ("confidence", models.FloatField(default=0.0)),
                ("evidence", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="model_coordination_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "multimodal_cross_insights",
                "ordering": ["created_at"],
            },
        ),
    ]
