# ruff: noqa
# Generated by Django 5.2.7 on 2025-11-22 13:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0003_remove_changelog_session_remove_changelog_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plugin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("integration", "Integration"),
                            ("tool", "Tool"),
                            ("data_source", "Data Source"),
                            ("notification", "Notification"),
                            ("analytics", "Analytics"),
                            ("custom_agent", "Custom Agent"),
                        ],
                        max_length=50,
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=200)),
                ("homepage", models.URLField(blank=True)),
                ("repository", models.URLField(blank=True)),
                ("config_schema", models.JSONField(default=dict)),
                ("default_config", models.JSONField(default=dict)),
                ("manifest", models.JSONField()),
                ("entry_point", models.CharField(max_length=500)),
                ("is_installed", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("download_count", models.IntegerField(default=0)),
                ("rating", models.FloatField(default=0.0)),
                ("rating_count", models.IntegerField(default=0)),
                ("dependencies", models.JSONField(default=list)),
                ("python_requirements", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "plugin",
                "ordering": ["-rating", "-download_count"],
            },
        ),
        migrations.CreateModel(
            name="CustomAgentPlugin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plugin_config", models.JSONField(default=dict)),
                ("capabilities", models.JSONField(default=list)),
                ("total_invocations", models.IntegerField(default=0)),
                ("success_rate", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_config",
                        to="agents.agent",
                    ),
                ),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_agents",
                        to="plugin_system.plugin",
                    ),
                ),
            ],
            options={
                "db_table": "custom_agent_plugin",
            },
        ),
        migrations.CreateModel(
            name="PluginInstallation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("custom_config", models.JSONField(default=dict)),
                ("is_enabled", models.BooleanField(default=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installations",
                        to="plugin_system.plugin",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_installations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "plugin_installation",
                "ordering": ["-installed_at"],
                "unique_together": {("plugin", "user")},
            },
        ),
        migrations.CreateModel(
            name="PluginAPIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("service_name", models.CharField(max_length=100)),
                ("api_key", models.CharField(max_length=500)),
                ("api_secret", models.CharField(blank=True, max_length=500)),
                ("additional_config", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="plugin_system.plugininstallation",
                    ),
                ),
            ],
            options={
                "db_table": "plugin_api_key",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PluginReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("review_text", models.TextField()),
                ("helpful_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="plugin_system.plugin",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "plugin_review",
                "ordering": ["-created_at"],
                "unique_together": {("plugin", "user")},
            },
        ),
    ]
