# ruff: noqa
# Generated by Django 5.2.7 on 2025-11-22 10:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentCoordinationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("sequential", "Sequential"),
                            ("parallel", "Parallel"),
                            ("hierarchical", "Hierarchical"),
                            ("collaborative", "Collaborative"),
                            ("competitive", "Competitive"),
                        ],
                        default="sequential",
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Coordination configuration"
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        default=dict, help_text="Shared context between agents"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordination_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_agent_id",
                    models.UUIDField(
                        help_text="ID of the agent initiating interaction"
                    ),
                ),
                (
                    "target_agent_id",
                    models.UUIDField(help_text="ID of the agent receiving interaction"),
                ),
                ("interaction_type", models.CharField(max_length=50)),
                ("content", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "coordination_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="Multi_agents_cordination.agentcoordinationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CoordinationMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metric_name", models.CharField(max_length=100)),
                ("metric_value", models.FloatField()),
                ("metadata", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "coordination_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="Multi_agents_cordination.agentcoordinationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="agentcoordinationsession",
            index=models.Index(
                fields=["user", "is_active"], name="Multi_agent_user_id_d62993_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentcoordinationsession",
            index=models.Index(
                fields=["strategy", "created_at"], name="Multi_agent_strateg_d39218_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentinteraction",
            index=models.Index(
                fields=["coordination_session", "created_at"],
                name="Multi_agent_coordin_387794_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentinteraction",
            index=models.Index(
                fields=["source_agent_id", "target_agent_id"],
                name="Multi_agent_source__ca99be_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coordinationmetric",
            index=models.Index(
                fields=["coordination_session", "metric_name"],
                name="Multi_agent_coordin_611ab1_idx",
            ),
        ),
    ]
