# ruff: noqa
# Generated by Django 5.2.7 on 2025-11-22 13:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0003_remove_changelog_session_remove_changelog_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("channel_type", models.CharField(max_length=50)),
                ("channel_name", models.CharField(max_length=200)),
                ("channel_config", models.JSONField()),
                ("subscribed_events", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_channel",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("description", models.TextField(blank=True)),
                ("subscribed_events", models.JSONField(default=list)),
                ("secret_key", models.CharField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("retry_on_failure", models.BooleanField(default=True)),
                ("max_retries", models.IntegerField(default=3)),
                ("timeout_seconds", models.IntegerField(default=30)),
                ("custom_headers", models.JSONField(default=dict)),
                ("total_deliveries", models.IntegerField(default=0)),
                ("successful_deliveries", models.IntegerField(default=0)),
                ("failed_deliveries", models.IntegerField(default=0)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "webhook_endpoint",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("session.created", "Session Created"),
                            ("session.completed", "Session Completed"),
                            ("session.failed", "Session Failed"),
                            ("task.created", "Task Created"),
                            ("task.completed", "Task Completed"),
                            ("task.failed", "Task Failed"),
                            ("agent.response", "Agent Response"),
                            ("workflow.started", "Workflow Started"),
                            ("workflow.completed", "Workflow Completed"),
                            ("error.occurred", "Error Occurred"),
                        ],
                        max_length=50,
                    ),
                ),
                ("event_data", models.JSONField()),
                ("source", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_logs",
                        to="agents.session",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_logs",
                        to="agents.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "event_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="event_log_event_t_e5e290_idx",
                    ),
                    models.Index(
                        fields=["session", "-created_at"],
                        name="event_log_session_5b54d1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("session.created", "Session Created"),
                            ("session.completed", "Session Completed"),
                            ("session.failed", "Session Failed"),
                            ("task.created", "Task Created"),
                            ("task.completed", "Task Completed"),
                            ("task.failed", "Task Failed"),
                            ("agent.response", "Agent Response"),
                            ("workflow.started", "Workflow Started"),
                            ("workflow.completed", "Workflow Completed"),
                            ("error.occurred", "Error Occurred"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("data", models.JSONField(default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="webhooks.notificationchannel",
                    ),
                ),
            ],
            options={
                "db_table": "notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_366c29_idx",
                    ),
                    models.Index(
                        fields=["is_read", "user"],
                        name="notificatio_is_read_78d402_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("session.created", "Session Created"),
                            ("session.completed", "Session Completed"),
                            ("session.failed", "Session Failed"),
                            ("task.created", "Task Created"),
                            ("task.completed", "Task Completed"),
                            ("task.failed", "Task Failed"),
                            ("agent.response", "Agent Response"),
                            ("workflow.started", "Workflow Started"),
                            ("workflow.completed", "Workflow Completed"),
                            ("error.occurred", "Error Occurred"),
                        ],
                        max_length=50,
                    ),
                ),
                ("payload", models.JSONField()),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("attempt_number", models.IntegerField(default=1)),
                ("retry_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="webhooks.webhookendpoint",
                    ),
                ),
            ],
            options={
                "db_table": "webhook_delivery",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["webhook", "-created_at"],
                        name="webhook_del_webhook_e1be2a_idx",
                    ),
                    models.Index(
                        fields=["event_type", "success"],
                        name="webhook_del_event_t_aa35e4_idx",
                    ),
                ],
            },
        ),
    ]
