# ruff: noqa
# Generated by Django 5.2.7 on 2025-11-22 13:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("session.created", "Session Created"),
                            ("session.completed", "Session Completed"),
                            ("session.failed", "Session Failed"),
                            ("task.created", "Task Created"),
                            ("task.completed", "Task Completed"),
                            ("task.failed", "Task Failed"),
                            ("agent.response", "Agent Response"),
                            ("workflow.started", "Workflow Started"),
                            ("workflow.completed", "Workflow Completed"),
                            ("error.occurred", "Error Occurred"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("data", models.JSONField(default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="webhooks.notificationchannel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "webhook_notification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.AddIndex(
            model_name="webhooknotification",
            index=models.Index(
                fields=["user", "-created_at"], name="webhook_not_user_id_a4e58e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhooknotification",
            index=models.Index(
                fields=["is_read", "user"], name="webhook_not_is_read_06452c_idx"
            ),
        ),
    ]
