# ruff: noqa
# Generated by Django 5.1.5 on 2025-09-28 10:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("REST", "REST API"),
                            ("GraphQL", "GraphQL"),
                            ("WebSocket", "WebSocket"),
                            ("Webhook", "Webhook"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Database", "Database"),
                            ("Cloud", "Cloud Services"),
                            ("Payment", "Payment Processing"),
                            ("Analytics", "Analytics"),
                            ("Social", "Social Media"),
                            ("AI/ML", "AI/ML Services"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("endpoint", models.URLField()),
                ("method", models.CharField(default="GET", max_length=10)),
                ("headers", models.JSONField(default=dict)),
                ("authentication", models.JSONField(default=dict)),
                ("parameters", models.JSONField(default=list)),
                ("rate_limit", models.JSONField(default=dict)),
                ("retry_policy", models.JSONField(default=dict)),
                ("timeout", models.IntegerField(default=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                        ],
                        default="inactive",
                        max_length=20,
                    ),
                ),
                ("last_tested", models.DateTimeField(blank=True, null=True)),
                ("success_rate", models.FloatField(default=0.0)),
                ("total_calls", models.BigIntegerField(default=0)),
                ("avg_response_time", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="APICallResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("timeout", "Timeout"),
                        ],
                        max_length=20,
                    ),
                ),
                ("response_data", models.JSONField(blank=True, null=True)),
                ("response_time", models.FloatField()),
                ("error_message", models.TextField(blank=True)),
                ("request_data", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_results",
                        to="api_integrations.apiintegration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="APITemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("popular", "Popular APIs"),
                            ("database", "Database APIs"),
                            ("cloud", "Cloud Services"),
                            ("social", "Social Media"),
                            ("payment", "Payment Services"),
                            ("ai_ml", "AI/ML Services"),
                            ("analytics", "Analytics"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(max_length=255)),
                ("logo", models.URLField(blank=True)),
                ("config_template", models.JSONField()),
                ("popularity", models.IntegerField(default=0)),
                ("tags", models.JSONField(default=list)),
                ("is_public", models.BooleanField(default=True)),
                ("documentation_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegrationAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("rule_triggered", models.CharField(max_length=255)),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="api_integrations.apiintegration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegrationUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_calls", models.IntegerField(default=0)),
                ("successful_calls", models.IntegerField(default=0)),
                ("failed_calls", models.IntegerField(default=0)),
                ("avg_response_time", models.FloatField(default=0.0)),
                ("total_data_transferred", models.BigIntegerField(default=0)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_stats",
                        to="api_integrations.apiintegration",
                    ),
                ),
            ],
        ),
    ]
