# ruff: noqa: RUF012
# ruff: noqa
# Generated by Django 5.2.7 on 2025-11-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012
        ("api_integrations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apiintegration",
            name="authentication",
        ),
        migrations.AddField(
            model_name="apiintegration",
            name="encrypted_auth_data",
            field=models.TextField(blank=True),
        ),
    ]
