# ruff: noqa
# Generated by Django 6.0 on 2026-06-28 08:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_integrations", "0002_remove_apiintegration_authentication_and_more"),
        ("workflow_builder", "0002_alter_workflowtemplate_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledAutomation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "automation_type",
                    models.CharField(
                        choices=[
                            ("inbox_digest", "Daily Inbox Digest"),
                            ("slack_alert", "Slack Alert"),
                            ("workflow_run", "Run Workflow"),
                            ("integration_check", "Integration Health Check"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "Every Hour"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("cron", "Custom Cron"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("cron_expression", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("config", models.JSONField(default=dict)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_automations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automations",
                        to="workflow_builder.visualworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
