# ruff: noqa: RUF012
# ruff: noqa
# Generated by Django 6.0 on 2026-07-25 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012
        ("api_integrations", "0003_scheduledautomation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apiintegration",
            options={"ordering": ["-created_at"]},
        ),
    ]
